""" Module for defining hyperparameters for various components of the system. """


def get_hyperparameters():
    """ Returns a dictionary of hyperparameters for various components of the system."""
    hyperparams = {
        'comments': 'those were generated by Copilot',
        'data_preprocess': {},
        'evaluation': {},
        'load_db': {
            'verbose': True,
        },
        'prompts': {
            'system': {
                'description': """The following text describes an e-commerce product.""",
                'json': """Present as a valid JSON object.""",
                'capitalization': """The key words must start capitalized.""",
                'structure': """All values are flat strings, meaning: they don't have any inner lists nor sub-json objects.""",
            },
            'examples': [
                {
                    'input': '''New Electric Flameless Torch Battery Windproof Lighter BBQ Picnic Camping No Gas Fuel Required Fire Starter''',
                    'output': '''{"Disposable": "No", "Automatic Alarming or Not (Kettle)": "No", "Category": "Lighter", "With Fuel or Not": "No", "With Wooden Handle or Not": "No"}'''
                },
                {
                    'input': '''Miyouj Leaves Print One Piece Swimsuit Female Off Shoulder Swimwear Women Bathing Suits Brazilian Bikini May Beach XL Monokini''',
                    'output': '''{"Sport Type": "Swim", "Model Number": "Monokini", "Gender": "Women", "Pattern Type": "Print", "one-piece suit": "Swimsuit Female", "Bathers": "Off Shoulder Swimwear", "Female Swimsuits": "Swimwear Women", "Monokini": "Women Bathing Suits", "Bathing Suit Women": "Monokini", "Women Swimwear": "Brazilian Bikini", "Swimwear 2018": "Bikini May Beach", "swimsuit Bathing Suit": "Brazilian Bikini"}'''
                },
                {
                    'input': '''Outdoor Travel Cooker Stoves Ultra-Light Spirit Alcohol Stove Camping Cooking Furnace''',
                    'output': '''{"Type": "Alcohol Stove"}'''
                }
            ]
        },
        'model': {
            'liquid': {
                'model_name': 'LiquidAI/LFM2-350M-Extract',
                'max_new_tokens': 160,
                'add_generation_prompt': True,
                'tokenize': True,
                'return_dict': True,
                'return_tensors': 'pt',
            }
        }
    }
    return hyperparams
